[tool.poetry]
name = "curso_python_EUD"
version = "0.1.0"
description = ""
authors = ["Andrés Felipe Sierra Parra <cepfelo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pytest = "^6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
